# This workflow will run on pull requests
name: Run Tests on Pull Requests
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies
      run: | 
        sudo apt-get install cmake protobuf-compiler wget redis-server

    - name: Install Miniconda3
      run: |
        echo $HOME
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
    - name: Run CMake and build
      working-directory: teraserver
      run: |
        cmake .
        make python-all

    - name: Run API Tests
      working-directory: teraserver/python
      run: |
        redis-server &
        sleep 1
        ./env/python-3.8/bin/python TeraServer.py --enable_tests=1 &
        sleep 5
        
        
        

        
      
    
